# Generated by Django 4.2.20 on 2025-05-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='skills',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
