# Generated by Django 4.2.20 on 2025-05-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupmate', '0002_student_details_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupmate.course'),
        ),
    ]
